version: '3.7'

services: 
  portainer:
    # 1.24.2 / 2.16.2
    image: portainer/portainer
    container_name: portainer 
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/portainer_data:/data
    tty: true

