services:
  portainer:
    # 1.24.2 / 2.16.2 / 2.19.5
    image: portainer/portainer-ce:2.20.3
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/portainer_data:/data
    tty: true

